app.version=0.1.1-beta
app.commit=8bffb4ecffeb05970234ac3318dd8f0ac9bee2ca
api.url=https://devflow.redstphillip.uk/api
github.owner=redstphillip
github.repo=devflow
github.branch=main
update.jar.url=https://raw.githubusercontent.com/redstphillip/devflow/main/updates/devflow-latest.jar
